spring:
  datasource:
    url: jdbc:mysql://<hostName>/<dbName>
    username: <id>
    password: <password>
    driver-class-name: com.mysql.cj.jdbc.Driver

file:
  dir: <파일 위치>

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: COOKIE
      timeout: 240
