spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/porkcutlet
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: COOKIE
      timeout: 240

file:
  dir: /Users/geonholee/Documents/개인프로젝트/cutletMasterRes/
